### ISSUE TITLE
Tries to connect to localhost

### ISSUE THREAD

**Issue by hackel** [freaktechnik/advanced-github-notifier#15]
I haven't had any luck getting this addon to work in FF52.  After installing, when I first clicked on the notification icon, it took me to GitHub and I granted it access.  Now when I click on the icon, it just opens a new tab to `https://localhost/github-auth?code=x&state=y`.  Obviously this does not work.  I've tried it with both 1.0 and 1.1.0pre1.
Browser console output:
```
15:33:34.447 TypeError: NetworkError when attempting to fetch resource.  background.js:239:29
	needsAuth/</< moz-extension://b34b1b7d-25b5-4376-ad57-5db075a9845f/scripts/background.js:239:29
	(Async: promise callback)
	needsAuth/< moz-extension://b34b1b7d-25b5-4376-ad57-5db075a9845f/scripts/background.js:208:13
15:33:34.451 “nsICookieManager2.getCookiesFromHost()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2  cookietracker.js:82:12
15:33:34.559 “nsICookieManager2.getCookiesFromHost()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2  cookietracker.js:82:12
15:33:34.595 Use of nsIFile in content process is deprecated.  bootstrap.js:36:40
```

**Comment by freaktechnik** [comment]
This is used as a OAuth callback until I can safely switch to the Firefox provided OAuth handler, which is not finalized to my knowledge.

It should, currently, however detect the URL and then close the tab. It seems that in this case the user is not properly authenticated and thus GitHub is redirecting to localhost, as at that stage in the code that part should already have taken place and I am not aware of any changes to the GitHub OAuth process since I implemented it for the extension. What happens if you click on the extension icon? If you don't get the tab to authorize, please uninstall the extension and re-install it.

**Comment by freaktechnik** [comment]
I don't think I can use the OAuth callback URL handler from Firefox, since I have to specify the redirect URL in the GitHub app configuration, however the URL generated by Firefox is not predictable from what I can tell.
