### ISSUE TITLE
No system notifications

### ISSUE THREAD

**Issue by tooomm** [freaktechnik/advanced-github-notifier#62]
The extension icon displays updates just fine and I see a red bubble with the notification count, but I don't see popup tile notifications from the browser anymore!
I used to see them which was awesome, but they are gone now since several days.

Running FF56 on Windows 10. `Show Notifications` enabled.

---

Edit: Since I use portable Firefox I double checked `Settings -> System -> Notifications & actions`, Firefox is not displayed as sender there at all. I blame the recent `1709` win update I applied recently. 
This might be the cause, since I don't see notifications for finished downloads, too. :(
Seems to be more likely than an update to FF56?

**Comment by freaktechnik** [comment]
Firefox does not show system notifications on Windows 10. It uses its own notification system that sometimes (especially when Firefox is maximized or multiple monitors are present) shows notifications "above" the display. It is supposed to show them downward from the top right corner when Firefox is maximized, but sometimes they go up instead of down, thus being invisible.
