### ISSUE TITLE
Add GitLab support

### ISSUE THREAD

**Issue by norpol** [freaktechnik/advanced-github-notifier#94]
First of all, thank you for this great extension - looks exactly of what I was looking for (not to miss Participating notifications anymore).

I've some experience with the GitLab API and I wonder if there is any interest in adding this functionality into this extension.

It would probably just display [Todos](https://docs.gitlab.com/ee/api/todos.html), which I think are the equivalent to "Notifications" in GitHub.

**Comment by freaktechnik** [comment]
Generally the extension should be able to handle that quite easily, depending on how authentication and storage for API credentials works. The extension handles the different ways of authenticating GitHub very modular, and I'd be more than happy to help you get started adding a handler for the GitLab things. Of course it'd expect the data that is stored for notifications to be in the GitHub format, but in the worst caseI'd be happy to adopt the internal format to something that works with both GitHub and GitLab.

Of course there'd be some other work, like making sure the correct icons are used etc. since the extension is currently very tailored to the GitHub language and visuals.
